### ISSUE TITLE
[Feature request] Expose resource name via transmartApp (or other means)

### ISSUE THREAD

**Issue by sherzinger** [i2b2-tranSMART/i2b2transmart-quick-start#5]
Would it be possible to expose the IRCT resource name so we can remove this option?

`FRACTALIS_RESOURCE_NAME=i2b2-wildfly-nhanes/Demo`

I don't like the idea of having to hardcode this value for every new dataset.
It's not a top priority, but it would be very nice to have.

**Comment by recursethis** [comment]
Sascha,

I was waiting for access to the new JIRA account. Since your feature request is application specific and not infrastructure/deployment specific, create a feature request here: https://jira.transmartfoundation.org/projects/I2B2TM/issues/I2B2TM-1?filter=allopenissues
