### ISSUE TITLE
Oracle database fails ..

### ISSUE THREAD

**Issue by vangalamaheshh** [i2b2-tranSMART/i2b2transmart-quick-start#6]
Hello @namdets and others -

Oracle db failed with the following error: (Any thoughts into how to fix this?)

db_1            | ORA-01157: cannot identify/lock data file 11 - see DBWR trace file
db_1            | ORA-01110: data file 11: '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/undotbs01.dbf'
db_1            | 
db_1            | 
db_1            | SQL> Disconnected from Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
db_1            | #####################################
db_1            | ########### E R R O R ###############
db_1            | DATABASE SETUP WAS NOT SUCCESSFUL!
db_1            | Please check output for further info!
db_1            | ########### E R R O R ###############
db_1            | #####################################
db_1            | The following output is now a tail of the alert.log:
db_1            | ORA-27046: file size is not a multiple of logical block size
db_1            | Additional information: 1
db_1            | 2018-06-15T16:12:49.516486+00:00
db_1            | Ping without log force is disabled:
db_1            |   instance mounted in exclusive mode.
db_1            | 2018-06-15T16:12:49.575528+00:00
db_1            | Errors in file /opt/oracle/diag/rdbms/orclcdb/ORCLCDB/trace/ORCLCDB_ora_97.trc:
db_1            | ORA-01157: cannot identify/lock data file 11 - see DBWR trace file
db_1            | ORA-01110: data file 11: '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/undotbs01.dbf'
db_1            | ORA-1157 signalled during: ALTER DATABASE OPEN...
db_1            | 2018-06-15T16:12:50.665390+00:00
db_1            | Errors in file /opt/oracle/diag/rdbms/orclcdb/ORCLCDB/trace/ORCLCDB_m000_99.trc:
db_1            | ORA-01110: data file 12: '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/users01.dbf'
db_1            | ORA-01565: error in identifying file '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/users01.dbf'
db_1            | ORA-27046: file size is not a multiple of logical block size
db_1            | Additional information: 1
db_1            | 2018-06-15T16:12:50.773235+00:00
db_1            | Errors in file /opt/oracle/diag/rdbms/orclcdb/ORCLCDB/trace/ORCLCDB_m000_99.trc:
db_1            | ORA-01110: data file 16: '/opt/oracle/oradata/ORCLCDB/5905C0194F7608C2E053020011ACA824/datafile/o1_mf_i2b2_ful_fjfmbvqh_.dbf'
db_1            | ORA-01565: error in identifying file '/opt/oracle/oradata/ORCLCDB/5905C0194F7608C2E053020011ACA824/datafile/o1_mf_i2b2_ful_fjf
mbvqh_.dbf'
db_1            | ORA-27046: file size is not a multiple of logical block size

**Comment by vangalamaheshh** [comment]
If it's helpful ...

[oracle@938ad689acf1 ORCLPDB1]$ du -hc *
361M    sysaux01.dbf
261M    system01.dbf
2.0G    temp01.dbf
2.0G    undotbs01.dbf
2.0G    users01.dbf
6.7G    total
[oracle@938ad689acf1 ORCLPDB1]$

There is the file "/opt/oracle/oradata/ORCLCDB/ORCLPDB1/undotbs01.dbf" with 2G written to it. I am not sure, why and where this stack trace coming from. 

Thanks,
Mahesh

**Comment by recursethis** [comment]
Make you please share `docker info`, `docker version`, `docker system df`

**Comment by vangalamaheshh** [comment]
@recursethis:

docker info:

Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-1019-gcp
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 12.71GiB
Name: i2b2-transmart-dev
ID: OSKR:IQMF:4H7Z:SVB7:GACB:DR6B:3ZER:YDJ7:4NXL:JKSV:N6HB:AKJN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support


--------------------------------------

docker version:

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
----------------------------------------

docker system df:

TYPE                TOTAL               ACTIVE              SIZE                RECLAIMABLE
Images              11                  1                   51.48GB             4.843GB (9%)
Containers          1                   1                   5.614MB             0B (0%)
Local Volumes       4                   2                   17.84GB             0B (0%)
Build Cache                                                 0B                  0B


Let me know.

Thanks,
Mahesh

**Comment by vangalamaheshh** [comment]
@recursethis -

Any update on this?

Thank you,
Mahesh

**Comment by recursethis** [comment]
@vangalamaheshh Lucky enough, today we ran specifically into this issue. We ran into this issue deploying the Oracle Database on CentOS 7.4. We were able to resolve the issue by changing the storage driver for Docker to `devicemapper`

We installed the dependencies: `device-mapper-persistent-data, lvm2`
We updated the /etc/docker/daemon.json:
```
{
  "storage-driver": "devicemapper",
  "storage-opts": [
    "dm.directlvm_device=/dev/xvdb",
    "dm.thinp_percent=95",
    "dm.thinp_metapercent=1",
    "dm.thinp_autoextend_threshold=80",
    "dm.thinp_autoextend_percent=20",
    "dm.directlvm_device_force=false",
    "dm.basesize=40G"
  ]
}
```
And restarted the Docker daemon `systemctl restart docker`

There are a few caveats, so make sure to follow the instructions here: https://docs.docker.com/storage/storagedriver/device-mapper-driver/

Make sure your OS is using the recommended storage driver for Docker: https://docs.docker.com/storage/storagedriver/select-storage-driver/
